name: 🏰Acceso a la Fortaleza Prohibida

on: push

jobs:
    acceso-a-la-base:
        runs-on: ubuntu-latest

        steps:
            - name: El agente llega a la Fortaleza
              run: |
                echo "Agente ${{github.actor}} llega a la Fortaleza"
                echo ""
                echo "Buscar los archivos de la Legión"
                ls -la
                echo ""
                echo "✖️ pero que pasó? no hay nada!"